### ISSUE TITLE
Mobile responsiveness 

### ISSUE THREAD

**Issue by Mikeysax** [dmk1991/splurty-verses#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

- Michael

**Comment by dmk1991** [comment]
Michael,

Thanks for bringing this up, I never even bothered to look at the site on my own phone.  Issue appears to have been resolved and mobile usage seems to be much more user friendly.

Let me know if your still having issues,

Dave
